### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by linjunjie1221** [AER-RC/solar-source-function#1]
Can you tell me the version of gcc you are using? The system I am using is ubantu, and the gcc version is 11.4.0. The following error is reported during compilation. I wonder if it is because the gcc version is too high.
<img width="366" alt="da1c7b2709d2d1def9089231c5bba22" src="https://github.com/AER-RC/solar-source-function/assets/51101874/d7273e78-5d6e-4a6c-b1f9-d9102a0b2862">

**Comment by pernak18** [comment]
@linjunjie1221 yes, that is likely the issue. we have only tested our models with older versions of `gfortran`. please see https://github.com/AER-RC/LBLRTM/issues/9 for suggestions on workarounds with other builds (i.e., usage of `-std=legacy` in the `Makefile`) and let us know if that helps with the SSF

**Comment by linjunjie1221** [comment]
> @linjunjie1221 yes, that is likely the issue. we have only tested our models with older versions of `gfortran`. please see [AER-RC/LBLRTM#9](https://github.com/AER-RC/LBLRTM/issues/9) for suggestions on workarounds with other builds (i.e., usage of `-std=legacy` in the `Makefile`) and let us know if that helps with the SSF

Thank you for your answer. The problem is solved perfectly. Thank you again for your reply.
